version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-teste-fullstack
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data

volumes:
  docker-data: